### ISSUE TITLE
Initial AccountsDB implementation 

### ISSUE THREAD

**Issue by 0xNineteen** [Syndica/sig#53]
need the implement the basic functionality of accounts-db 
- loading and indexing accounts from snapshot data 
- verifying data correctness 
- loading system accounts and sysvars

progress: 
- [x] deserialize snapshot metadata (#40)
- [x] load snapshot accounts (#42) 
- [x] account indexing (#54)
- [x] loading sysvars (#56)
- [x] support incremental snapshots (#58)
- [x] write accounts functionality
- [x] setup rust-client benchmarking 
- [x] benchmark (reads, writes)
- [x] disk-based indexing
- [x] larger benchmarks (accounts stored on disk) 
- [x] disk-based indexing benchmarks
- [x] improve disk-based indexing for reads
- [x] improve hashmap performance 
- [x] improve snapshot loading 
- [x] re-run benchmarks (and improve upon rust client)
- [x] more advanced benchmarks (multiple slot lists, larger initial accounts before benchmarking writes, ...)
- [x] improve snapshot reading (.tar.zstd format is slow right now) 
- [ ] improve memory allocations + fix leaks (current impl is inefficient right now + FBA sucks at free-ing memory)
- [ ] add additional account cleaning (/reclaims/swapping states which come from the same slot)
- [ ] snapshot downloads via gossip
