### ISSUE TITLE
feat(repair): 3 - snapshot data: leader schedule, root slot

### ISSUE THREAD

**Issue by dnut** [Syndica/sig#84]
### description

Get this from the snapshot and feed it into repair:
- leader schedule -> use for signature verification
- root slot -> initialize the shred tracker

### tasks
- [x] port cha-cha random generator from rust
- [x] compute leader schedule using chacha
- [x] get root slot from snapshot and pass it into shred tracker (temporary blockstore stand-in)

### time estimate: 
- 2-3 days

due: wednesday may16

### links:
old plan: https://docs.google.com/document/d/1TPGWTOaACFJqoR_jShxjzE5I2sLtKfG01PwTjg7N4ec
